### ISSUE TITLE
Make firefly support a config file

### ISSUE THREAD

**Issue by anandology** [rorodata/firefly#11]
It should be possible to specify the specs in an yaml config file instead of passing all command-line arguments. Plan for more options for each function, like output-content-type, input-content-type, endpoint etc.

It would be better to have a version field to the config file so that we can handle old versions if we change the format in future.

**Comment by palnabarun** [comment]
Currently supported features can be exposed via this example config:
```
version: 1
functions:
    square:
        path: "/square"
        source: "funcs.square"
    cube:
        path: "/cube"
        source: "funcs.cube"
```
