### ISSUE TITLE
Client should use the path from function specs when calling a remote function

### ISSUE THREAD

**Issue by anandology** [rorodata/firefly#58]
The client currently constructs the path to request by appending the function name to the base_url, even though the server specified a separate path for that function. 

For example, if we start a server using the following configuration, the client will not be able to call the function hello.

```
functions:
    hello:
        path: /h
        function: hello.hello
```
